import 'package:ride_hub/model/brand.dart';
import 'package:ride_hub/model/car_category.dart';
import 'package:ride_hub/model/reviews_model.dart';
import '../model/car.dart';
import '../model/office.dart';
List<CarCategory>categories=[CarCategory(name:"Economic Cars"),CarCategory(name:"Electric cars"),CarCategory(name:"Luxury cars"),CarCategory(name:"Buses and public transportation")];

List<Office> economicOffices = [
  Office(
    name: 'Office 1',
    imgLink: 'assets/testImages/carOffice1.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 2',
    imgLink: 'assets/testImages/carOffice2.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 3',
    imgLink: 'assets/testImages/carOffice3.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 4',
    imgLink: 'assets/testImages/carOffice4.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 5',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 6',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 7',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 8',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 9',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 10',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
];

List<Office> electricOffices = [
  Office(
    name: 'Office 1',
    imgLink: 'assets/testImages/carOffice1.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 2',
    imgLink: 'assets/testImages/carOffice2.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 3',
    imgLink: 'assets/testImages/carOffice3.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 4',
    imgLink: 'assets/testImages/carOffice4.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 5',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 6',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 7',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 8',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 9',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 10',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
];
List<Office> luxuryOffices = [
  Office(
    name: 'Office 1',
    imgLink: 'assets/testImages/carOffice1.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 2',
    imgLink: 'assets/testImages/carOffice2.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 3',
    imgLink: 'assets/testImages/carOffice3.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 4',
    imgLink: 'assets/testImages/carOffice4.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 5',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 6',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 7',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 8',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 9',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 10',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
];
List<Office> busesOffices = [
  Office(
    name: 'Office 1',
    imgLink: 'assets/testImages/carOffice1.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 2',
    imgLink: 'assets/testImages/carOffice2.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 3',
    imgLink: 'assets/testImages/carOffice3.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 4',
    imgLink: 'assets/testImages/carOffice4.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 5',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 6',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 7',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 8',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 9',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
  Office(
    name: 'Office 10',
    imgLink: 'assets/testImages/carOffice5.png',
    rate: 4,
    numberOfReservations: 200,
    reviews: 200,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    phoneNumber: '07XXXXXXXX',
    location: 'Amman',
  ),
];
List<Car> cars = [
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/car5.png',
      'assets/testImages/car5.png',
      'assets/testImages/car1.png',
      'assets/testImages/car5.png',
      'assets/testImages/car5.png',
      'assets/testImages/car1.png',
      'assets/testImages/car5.png',
      'assets/testImages/car5.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '00-123909889787', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '123', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '123', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '123', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '123', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car1.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota',
    year: 2020,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'blue', carNumber: '123', transmissionType: '1', performanceScore: 2,
  ),
  Car(
    name: 'Maserati',
    imagesLinks: [
      'assets/testImages/car2.png',
      'assets/testImages/carDet.png',
      'assets/testImages/carDet2.png'
    ],
    model: 'Toyota2',
    year: 2024,
    rentCost: 85,
    engineCapacity: 2.5,
    engineType: '4-cylinder (203–206 hp)',
    fuel: ' ~29–41 mpg (city/highway)',
    hoursPower: 225,
    seatCapacity: 4,
    mileage: 3000,
    generalInfo:
    'Lorem ipsum simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    reviews: 3,
    rate: 4,
    price: 0,
    dateOfAdd: '23/6/2025', color: 'red', carNumber: '3456', transmissionType: '2', performanceScore:45,
  ),
];
List<ReviewsModel>carReviews=[
  ReviewsModel(name:"Ali", review:"What a nice car", date:"23/06/2025", starNumber:5),
  ReviewsModel(name:"mosa", review:"good car", date:"30/06/2025", starNumber:4),
  ReviewsModel(name:"leen", review:" think is may good car", date:"03/06/2025", starNumber:3),
  ReviewsModel(name:"kareem", review:" bad car", date:"13/05/2025", starNumber:2),
  ReviewsModel(name:"sami", review:" worse car", date:"13/04/2025", starNumber:1),
  ReviewsModel(name:"sami", review:" worse car", date:"13/04/2025", starNumber:0),
  ReviewsModel(name:"Ali", review:"What a nice car", date:"23/06/2025", starNumber:5),
  ReviewsModel(name:"mosa", review:"good car", date:"30/06/2025", starNumber:4),
  ReviewsModel(name:"leen", review:" think is may good car", date:"03/06/2025", starNumber:3),
  ReviewsModel(name:"kareem", review:" bad car", date:"13/05/2025", starNumber:2),
  ReviewsModel(name:"sami", review:" worse car", date:"13/04/2025", starNumber:1),
  ReviewsModel(name:"sami", review:" worse car", date:"13/04/2025", starNumber:0),
];
List<Brand>brands=[
  Brand(brandName:"BMW",imgLink:"assets/images/test_images/bmw_logo.png"),
  Brand(brandName:"mercedes",imgLink:"assets/images/test_images/mercedes_logo.png"),
  Brand(brandName:"porsche",imgLink:"assets/images/test_images/porsche_logo.png"),
  Brand(brandName:"renault",imgLink:"assets/images/test_images/renault_logo.png"),
  Brand(brandName:"BMW",imgLink:"assets/images/test_images/bmw_logo.png"),
  Brand(brandName:"mercedes",imgLink:"assets/images/test_images/mercedes_logo.png"),
  Brand(brandName:"porsche",imgLink:"assets/images/test_images/porsche_logo.png"),
  Brand(brandName:"renault",imgLink:"assets/images/test_images/renault_logo.png"),
  Brand(brandName:"BMW",imgLink:"assets/images/test_images/bmw_logo.png"),
  Brand(brandName:"mercedes",imgLink:"assets/images/test_images/mercedes_logo.png"),
  Brand(brandName:"porsche",imgLink:"assets/images/test_images/porsche_logo.png"),
  Brand(brandName:"renault",imgLink:"assets/images/test_images/renault_logo.png"),



];
